#!/usr/bin/env python3
#
# CS3700, Fall 2021
# TCP Project Starter Code

# TODO:
# Queue for non-continous packets

import datetime
import json
import sys
import socket

from base64 import b64decode
import base64


def log(string):
  sys.stderr.write(datetime.datetime.now().strftime("%H:%M:%S.%f") + " " + string + "\n")

MSG_SIZE = 1500
TIMEOUT = 30

# Bind to localhost and an ephemeral port
UDP_IP = "127.0.0.1"
UDP_PORT = int(sys.argv[1])

# Set up the socket
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM) 
sock.bind((UDP_IP, UDP_PORT))
sock.settimeout(TIMEOUT)

# Get port we bound to
UDP_PORT = sock.getsockname()[1]
log("[bound] " + str(UDP_PORT))

# Last seen ACK
lastSeenACK = {}
seen_acks = []
received_packets = []
min_expected_seq = 0
max_expected_seq = 7000
num_packets_received_in_range = 0

# Now listen for packets
while True:
  result = sock.recvfrom(MSG_SIZE)

  # If nothing is ready, we hit the timeout
  if result:
    (data, addr) = result

    try:
      decoded = json.loads(data.decode())
      decodedData = base64.b64decode(decoded['data'].encode('ascii'))
      # If the EOF flag is set, exit
      if (decoded['eof']):
        log("[completed]")
        sys.exit(0)

      got_expected_packet = decoded['sequence'] >= min_expected_seq and decoded['sequence'] <= max_expected_seq

      # If there is data, we accept it and print it out
      if (decodedData and got_expected_packet and not decoded['sequence'] in seen_acks):
        num_packets_received_in_range += 1
        if num_packets_received_in_range == 8:
          min_expected_seq += 8000
          max_expected_seq += 8000
          num_packets_received_in_range = 0

          received_packets.sort(key=lambda p: p['sequence'])
          for packet in received_packets:
            data = base64.b64decode(packet['data'].encode('ascii'))
            sys.stdout.buffer.write(data)
          received_packets = []
        else:
          received_packets.append(decoded)
          
        seen_acks.append(decoded['sequence'])
        log("[recv data] " + str(decoded['sequence']) +
            " (" + str(len(decodedData)) + ") ACCEPTED (in-order)")

      # Store last seen ack.
      # if got_expected_packet:
      lastSeenACK = {"ack": decoded['sequence'] + len(decodedData)}

      if sock.sendto(json.dumps(lastSeenACK).encode(), addr) < len(lastSeenACK):
          log("[error] unable to fully send packet")


    except (ValueError, KeyError, TypeError) as e:
      log("[recv corrupt packet]")
      raise e
  else:
    log("[error] timeout")
    sys.exit(-1)
