#!/usr/bin/env python3
#
# CS3700, Fall 2021
# TCP Project Starter Code

# TODO:
# Queue for non-continous packets

import datetime
import json
import sys
import socket

from base64 import b64decode
import base64


def log(string):
  sys.stderr.write(datetime.datetime.now().strftime("%H:%M:%S.%f") + " " + string + "\n")

MSG_SIZE = 1500
TIMEOUT = 30

# Bind to localhost and an ephemeral port
UDP_IP = "127.0.0.1"
print(sys.argv[1])
UDP_PORT = int(sys.argv[1])

# Set up the socket
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM) 
sock.bind((UDP_IP, UDP_PORT))
sock.settimeout(TIMEOUT)

# Get port we bound to
UDP_PORT = sock.getsockname()[1]
log("[bound] " + str(UDP_PORT))

# Now listen for packets
while True:
  result = sock.recvfrom(MSG_SIZE)

  # If nothing is ready, we hit the timeout
  if result:
    (data, addr) = result

    try:
      print(data)
      decoded = json.loads(data.decode())
      decodedData = base64.b64decode(decoded['data'].encode('ascii'))

      # If the EOF flag is set, exit
      if (decoded['eof']):
        log("[completed]")
        sys.exit(0)

      # If there is data, we accept it and print it out
      if (decodedData):
        # If we receive data, we assume it's in-order
        # You will need to do much more here
        log("[recv data] " + str(decoded['sequence']) + " (" + str(len(decodedData)) + ") ACCEPTED (in-order)")
        sys.stdout.buffer.write(base64.b64encode(decodedData))

      # Send back an ack to the sender
      print('recv sequence')
      print('decoded {} len decoded {}'.format(decoded['sequence'], len(decodedData)))
      msg = json.dumps({"ack": decoded['sequence'] + len(decodedData)})
      log("ABOUT TO SEND " + msg)
      if sock.sendto(msg.encode(), addr) < len(msg):
        log("[error] unable to fully send packet")

    except (ValueError, KeyError, TypeError) as e:
      log("[recv corrupt packet]")
      raise e
  else:
    log("[error] timeout")
    sys.exit(-1)
