#!/usr/bin/python3
#
# CS3700, Fall 2021
# TCP Project Starter Code
#

# TODO:
# Slow start
# Congestion Control
# Retransmission
# Handshaking
# Flow control
# Window scaling

import datetime
import json
import sys
import socket

from base64 import b64encode
import base64


MSG_SIZE = 1500
DATA_SIZE = 1000
TIMEOUT = 0.75
SEQUENCE = 0

acks = []
sent_packets = {}
cwnd = 8
ssthresth = 16

# Bind to localhost and an ephemeral port
IP_PORT = sys.argv[1]
UDP_IP = IP_PORT[0:IP_PORT.find(":")]
UDP_PORT = int(IP_PORT[IP_PORT.find(":")+1:])
dest = (UDP_IP, UDP_PORT)

# Set up the socket
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM) 
sock.settimeout(TIMEOUT)

def log(string):
  sys.stderr.write(datetime.datetime.now().strftime("%H:%M:%S.%f") + " " + string + "\n")

expected_acks = []
def send_next_packet():
  global SEQUENCE

  data = sys.stdin.buffer.read(DATA_SIZE)
  if (len(data) > 0):
    obj = {"sequence": SEQUENCE, "data": base64.b64encode(data).decode('ascii'),
           "ack": False, "eof": False}
    msg = json.dumps(obj)
    SEQUENCE += len(data)
    sent_packets[SEQUENCE] = obj
    expected_acks.append(SEQUENCE)

    if sock.sendto(msg.encode(), dest) < len(msg):
      log("[error] unable to fully send packet")
    else:
      log("[send data] " + str(obj['sequence']) + " (" + str(len(data)) + ")")
    return True
  else:
    return False

# Send first packet
send_next_packet()

def updateSlowStart():
  global cwnd
  if (int(cwnd) < ssthresth):
    cwnd = cwnd + 1
  else:
    cwnd = cwnd + 1 / cwnd;


def send_next_packets():
  expected_acks = []
  if (not send_next_packet()):
    return False
  for x in range(1, int(cwnd)):
    send_next_packet()
  return True

# Now read in data, send packets
while True:
  log("ABOUT TO SLEEP")
  try:
    result = sock.recvfrom(MSG_SIZE)
  except socket.timeout:
    # ssthresth = cwnd / 2
    # cwnd = cwnd / 2 if cwnd > 2 else cwnd

    # sorted_sequences_so_far = list(sent_packets.keys())
    # sorted_sequences_so_far.sort(reverse=True)
    # print('sorted_sequences_so_far')
    # print(sorted_sequences_so_far)
    # highest_seq_so_far = sorted_sequences_so_far[0]
    if len(expected_acks) != 0:
      packet = sent_packets[expected_acks[0]]
      decodedData = base64.b64decode(packet['data'].encode('ascii'))
      if sock.sendto(json.dumps(packet).encode(), dest) < len(packet):
        log("IN TIMEOUT RESEND [error] unable to fully send packet")
      else:
        log("IN TIMEOUT RESEND [send data] " + str(packet['sequence']) + " (" + str(len(decodedData)) + ")")
      continue
    else:
      print('expected acks length is 0 on timeout, something went wrong')

  if result:
    (data, addr) = result
    try:
      decoded = json.loads(data)
      # If there is an ack, send next packet
      acks.append(decoded['ack'])
      #updateSlowStart()
      if decoded['ack'] <= SEQUENCE:
        log("[recv ack] " + str(decoded['ack']))
        if decoded['ack'] in expected_acks:
          expected_acks.remove(decoded['ack'])
        # Try to send next packets; break if no more data
        print('expected_acks')
        print(expected_acks)
        if (len(expected_acks) == 0 and not send_next_packets()):
          break
      elif len(acks) >= 3:
        last_3 = acks[-3:]
        if last_3.count(last_3[0]) == len(last_3):
          print('RESENDING PACKETS BC 3 DUPLICATE ACKS')
          print(acks)
          # we have 3 duplicate ACKS
          # send back the packet with this sequence + 1
          print('sequence to send')
          last_3_decoded_data = base64.b64decode(
              sent_packets[last_3[0]]['data'].encode('ascii'))
          sequence_to_send = last_3[0] + len(last_3_decoded_data)
          print('sequence to send')
          print(sequence_to_send)
          print(sent_packets.keys())
          keys_of_packets_to_send = list(filter(
              lambda p: p >= sequence_to_send, list(sent_packets.keys())))
          packets_to_send = []
          for key in keys_of_packets_to_send:
            packets_to_send.append(sent_packets[key])
          print(len(packets_to_send))
          SEQUENCE = sequence_to_send
          decodedData = base64.b64decode(decoded['data'].encode('ascii'))
          for packet in packets_to_send:
            if sock.sendto(json.dumps(packet).encode(), dest) < len(packet):
              log("IN RESEND [error] unable to fully send packet")
            else:
              log("IN RENSEND [send data] " + str(packet['sequence']) +
                  " (" + str(len(decodedData)) + ")")
            SEQUENCE += len(decodedData)

    except (ValueError, KeyError, TypeError):
      log("[recv corrupt packet]")
  else:
    log("[error] timeout")
    sys.exit(-1)

sock.sendto(json.dumps({"eof": True, "data": base64.b64encode(
    b'').decode('ascii'), "sequence": SEQUENCE, "ack": False}).encode(), dest)
sys.exit(0)
